name: Pre-Commit

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_HOME: .pre-commit
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: |
            .mypy_cache
            .pre-commit
          key: ${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: "Setup Poetry"
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: "Run Pre-Commit"
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
